packages:
  - 'packages/*'
  - 'shell/'
allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  nx: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@lizuz/mini-app-types@1.0.0 || 1.0.8'
