import type { OldModuleManifest } from "@sewa/host-platform";

export const FALLBACK_MINI_APPS: OldModuleManifest[] = [
  {
    id: "test-mini-app",
    name: "Test Mini App",
    description:
      "This mini app contain all the basic operations that can be perform thorough any mini app.",
    vendor: "Sawroz",
    version: "2.1.0",
    sdkVersion: "1.0.0",
    icon: "🎯",
    color: "#dc9a0d",
    category: "Playground",
    route: "/test",
    requiredPermissions: [],
    miniAppCapabilities: [],
    dataCapabilities: ["device.location"],
    isEnabled: true,
    order: 1,
    bundleUrl: "https://test-mini-app-orcin.vercel.app/",
    // bundleUrl: "http://localhost:3002/",
    entryType: "framework-agnostic",
    loadStrategy: "plugin",
    compatibility: {
      minShellVersion: "1.0.0",
      minSdkVersion: "1.0.0",
      supportedPlatforms: ["web"],
      supportedFrameworks: ["react"],
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "chat-mini-app",
    name: "Chat Mini App",
    description:
      "This chat mini app in react framework contain all the basic operations that can be perform thorough any mini app.",
    vendor: "Sawroz",
    version: "2.1.0",
    sdkVersion: "1.0.0",
    icon: "🟢",
    color: "#dc9a0d",
    category: "Playground",
    route: "/chat-mini-app",
    requiredPermissions: [],
    capabilities: [
      "auth",
      "chat",
      "ai",
      "permissions",
      "flags",
      "config",
      "navigation",
      "platform",
      "device",
      "api",
      "storage",
      "http",
      "events",
    ],
    miniAppCapabilities: ["http", "http.stream"],
    dataCapabilities: ["device.location"],
    isEnabled: true,
    order: 1,
    bundleUrl: "https://chat-mini-app-ten.vercel.app/",
    // bundleUrl: "http://localhost:3009/",
    entryType: "framework-agnostic",
    loadStrategy: "plugin",
    compatibility: {
      minShellVersion: "1.0.0",
      minSdkVersion: "1.0.0",
      supportedPlatforms: ["web"],
      supportedFrameworks: ["vue"],
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "veu-mini-app",
    name: "Veu Mini App",
    description:
      "This mini app in veu framework contain all the basic operations that can be perform thorough any mini app.",
    vendor: "Sawroz",
    version: "2.1.0",
    sdkVersion: "1.0.0",
    icon: "🟢",
    color: "#dc9a0d",
    category: "Playground",
    route: "/veu-mini-app",
    requiredPermissions: [],
    capabilities: [
      "auth",
      "chat",
      "ai",
      "permissions",
      "flags",
      "config",
      "navigation",
      "platform",
      "device",
      "api",
      "storage",
      "http",
      "events",
    ],
    isEnabled: true,
    order: 1,
    bundleUrl: "https://vue-mini-app-eta.vercel.app/",
    // bundleUrl: "http://localhost:4000/",
    entryType: "framework-agnostic",
    loadStrategy: "plugin",
    compatibility: {
      minShellVersion: "1.0.0",
      minSdkVersion: "1.0.0",
      supportedPlatforms: ["web"],
      supportedFrameworks: ["vue"],
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "next-mini-app",
    name: "Next Mini App",
    description:
      "This mini app in next framework contain all the basic operations that can be perform thorough any mini app.",
    vendor: "Sawroz",
    version: "2.1.0",
    sdkVersion: "1.0.0",
    icon: "🟡",
    color: "#dc9a0d",
    category: "Playground",
    route: "/next-mini-app",
    requiredPermissions: [],
    capabilities: [
      "auth",
      "chat",
      "ai",
      "permissions",
      "flags",
      "config",
      "navigation",
      "platform",
      "device",
      "api",
      "storage",
      "http",
      "events",
    ],
    isEnabled: true,
    order: 1,
    bundleUrl: "https://next-mini-app-sx38-rosy.vercel.app/",
    // bundleUrl: "http://localhost:3005/",
    entryType: "framework-agnostic",
    loadStrategy: "plugin",
    compatibility: {
      minShellVersion: "1.0.0",
      minSdkVersion: "1.0.0",
      supportedPlatforms: ["web"],
      supportedFrameworks: ["next"],
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "angular-mini-app",
    name: "Angular Mini App",
    description:
      "This mini app in angular framework contain all the basic operations that can be perform thorough any mini app.",
    vendor: "Sawroz",
    version: "2.1.0",
    sdkVersion: "1.0.0",
    icon: "🔴",
    color: "#dc9a0d",
    category: "Playground",
    route: "/angular-mini-app",
    requiredPermissions: [],
    capabilities: [
      "auth",
      "chat",
      "ai",
      "permissions",
      "flags",
      "config",
      "navigation",
      "platform",
      "device",
      "api",
      "storage",
      "http",
      "events",
    ],
    isEnabled: true,
    order: 1,
    bundleUrl: "https://angular-mini-app.vercel.app/",
    // bundleUrl: "http://localhost:4001/",
    entryType: "framework-agnostic",
    loadStrategy: "plugin",
    compatibility: {
      minShellVersion: "1.0.0",
      minSdkVersion: "1.0.0",
      supportedPlatforms: ["web"],
      supportedFrameworks: ["angular"],
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "nuxt-mini-app",
    name: "Nuxt Mini App",
    description:
      "This mini app in nuxt framework contain all the basic operations that can be perform thorough any mini app.",
    vendor: "Sawroz",
    version: "2.1.0",
    sdkVersion: "1.0.0",
    icon: "⚫",
    color: "#dc9a0d",
    category: "Playground",
    route: "/nuxt-mini-app",
    requiredPermissions: [],
    capabilities: [
      "auth",
      "chat",
      "ai",
      "permissions",
      "flags",
      "config",
      "navigation",
      "platform",
      "device",
      "api",
      "storage",
      "http",
      "events",
    ],
    isEnabled: true,
    order: 1,
    bundleUrl: "https://nuxt-mini-app-orcin.vercel.app/",
    // bundleUrl: "http://localhost:3006/",
    entryType: "framework-agnostic",
    loadStrategy: "plugin",
    compatibility: {
      minShellVersion: "1.0.0",
      minSdkVersion: "1.0.0",
      supportedPlatforms: ["web"],
      supportedFrameworks: ["nuxt"],
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "solid-mini-app",
    name: "Solid Mini App",
    description:
      "This mini app in solid framework contain all the basic operations that can be perform thorough any mini app.",
    vendor: "Sawroz",
    version: "2.1.0",
    sdkVersion: "1.0.0",
    icon: "🔵",
    color: "#dc9a0d",
    category: "Playground",
    route: "/solid-mini-app",
    requiredPermissions: [],
    capabilities: [
      "auth",
      "chat",
      "ai",
      "permissions",
      "flags",
      "config",
      "navigation",
      "platform",
      "device",
      "api",
      "storage",
      "http",
      "events",
    ],
    isEnabled: true,
    order: 1,
    bundleUrl: "https://solid-mini-app.vercel.app/",
    // bundleUrl: "http://localhost:3007/",
    entryType: "framework-agnostic",
    loadStrategy: "plugin",
    compatibility: {
      minShellVersion: "1.0.0",
      minSdkVersion: "1.0.0",
      supportedPlatforms: ["web"],
      supportedFrameworks: ["solid"],
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "svelte-mini-app",
    name: "Svelte Mini App",
    description:
      "This mini app in Svelte framework contain all the basic operations that can be perform thorough any mini app.",
    vendor: "Sawroz",
    version: "2.1.0",
    sdkVersion: "1.0.0",
    icon: "🟣",
    color: "#dc9a0d",
    category: "Playground",
    route: "/svelte-mini-app",
    requiredPermissions: [],
    capabilities: [
      "auth",
      "chat",
      "ai",
      "permissions",
      "flags",
      "config",
      "navigation",
      "platform",
      "device",
      "api",
      "storage",
      "http",
      "events",
    ],
    isEnabled: true,
    order: 1,
    bundleUrl: "https://svelte-mini-app.vercel.app/",
    // bundleUrl: "http://localhost:3008/",
    entryType: "framework-agnostic",
    loadStrategy: "plugin",
    compatibility: {
      minShellVersion: "1.0.0",
      minSdkVersion: "1.0.0",
      supportedPlatforms: ["web"],
      supportedFrameworks: ["svelte"],
    },
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
];
