"use client";

import type { PlatformEvent } from "@sewa/host-platform";
import { PLATFORM_EVENTS } from "@sewa/host-platform";
import { useCallback, useEffect, useRef } from "react";
import { usePlatform } from "@/context";

const BACK_TRAP_KEY = "__sewaMiniAppBackTrap";

type HistoryState = Record<string, unknown> | null;

export interface UseMiniAppBackButtonOptions {
  /**
   * Called when the mini app declines the press — it has no route left
   * to pop, so leaving the container is the shell's job.
   */
  onExit: () => void;

  /**
   * Skip while the mini app hasn't mounted yet.
   */
  enabled?: boolean;
}

/**
 * Routes the browser back button through the mounted mini app first.
 *
 * Browser history:
 *
 *   Host route
 *      ↓
 *   Mini app container
 *      ↓
 *   [BACK SENTINEL]
 *
 * Mini app MemoryRouter:
 *
 *   /user
 *      ↓
 *   /user/profile
 *      ↓
 *   /user/profile/12
 *
 * Browser back:
 *
 *   1. Browser pops the sentinel.
 *   2. Host immediately restores the sentinel with history.forward().
 *   3. Host asks the mini app to handle back.
 *   4. Mini app navigates its MemoryRouter backwards.
 *   5. Sentinel stays in place.
 *
 * If the mini app has no history left, it returns consumed=false
 * and the host exits the mini app.
 */
export function useMiniAppBackButton({ onExit, enabled = true }: UseMiniAppBackButtonOptions) {
  const { services, eventBus } = usePlatform();

  const onExitRef = useRef(onExit);

  /**
   * True while we're restoring the sentinel with history.forward().
   *
   * The popstate generated by history.forward() must NOT be treated
   * as another user back press.
   */
  const restoringTrapRef = useRef(false);

  /**
   * Prevent multiple browser-back events from being processed while
   * the previous one is still being handled.
   */
  const handlingBackRef = useRef(false);

  useEffect(() => {
    onExitRef.current = onExit;
  }, [onExit]);

  /**
   * Add the browser history sentinel.
   *
   * Important:
   * We only ever want ONE sentinel.
   */
  const armTrap = useCallback(() => {
    const state = (window.history.state as HistoryState & { idx?: number }) || {};

    if ((state as HistoryState)?.[BACK_TRAP_KEY]) {
      return;
    }

    // Preserve Next.js's existing history state and keep the hash-history
    // idx in sync. HashRouter (createHashHistory) stores `idx` in state and
    // increments it on every push. If we push the sentinel without bumping
    // idx, the next hash push will duplicate the index and `getIndex()` will
    // return the wrong delta on POP.
    const nextIdx = typeof state.idx === "number" ? state.idx + 1 : 1;
    window.history.pushState(
      {
        ...state,
        [BACK_TRAP_KEY]: true,
        idx: nextIdx,
      },
      "",
      window.location.href,
    );
  }, []);

  useEffect(() => {
    if (!enabled) {
      return;
    }

    const navigation = services.navigation;

    /**
     * The mini app reports its MemoryRouter state to the host.
     *
     * Example:
     *
     * /user                -> canGoBack: false
     * /user/profile        -> canGoBack: true
     * /user/profile/12     -> canGoBack: true
     */
    const unsubscribeRouteChanged = eventBus.subscribe(
      PLATFORM_EVENTS.NAVIGATION_CHANGED,
      (event: PlatformEvent) => {
        if (event.source === "shell") {
          return;
        }

        const payload = event.payload as { canGoBack?: boolean } | undefined;

        if (typeof payload?.canGoBack === "boolean") {
          navigation.setCanGoBack(payload.canGoBack);
        }
      },
    );

    /**
     * Restore the sentinel after the browser has popped it.
     *
     * Browser Back:
     *
     *   MiniApp → SENTINEL
     *              ↓ Back
     *   MiniApp
     *
     * history.forward():
     *
     *   MiniApp
     *      ↓
     *   MiniApp → SENTINEL
     *
     * We wait for the forward navigation to actually finish before
     * asking the mini app to handle the back operation.
     */
    const restoreTrap = (): Promise<void> => {
      return new Promise((resolve, reject) => {
        let settled = false;
        const timer = setTimeout(() => {
          window.removeEventListener("popstate", handleRestored);
          if (!settled) {
            settled = true;
            restoringTrapRef.current = false;
            reject(new Error("restoreTrap timed out"));
          }
        }, 500);

        const handleRestored = () => {
          if (settled) return;
          settled = true;
          clearTimeout(timer);
          window.removeEventListener("popstate", handleRestored);
          restoringTrapRef.current = false;
          resolve();
        };

        restoringTrapRef.current = true;
        window.addEventListener("popstate", handleRestored);
        window.history.forward();
      });
    };

    const handlePopState = async () => {
      /**
       * Ignore the popstate generated by our own history.forward().
       *
       * This is technically handled by restoreTrap(), but keeping this
       * guard makes the intent explicit and protects against re-entry.
       */
      if (restoringTrapRef.current) {
        return;
      }

      /**
       * Ignore another Back press while the previous Back operation
       * is still being processed.
       */
      if (handlingBackRef.current) {
        return;
      }

      // HashRouter stores the mini-app route in `location.hash` and creates
      // real browser entries via pushState (see createHashHistory). Those
      // hash entries must NOT be treated as sentinel pops. When the mini-app
      // has history (`canGoBack`) and the URL is hash-routed, a pop is just
      // the browser popping a hash entry — let it happen naturally. The
      // mini-app's HashRouter will see the POP and tell the host the new
      // `canGoBack` via ROUTE_CHANGED. Only when the mini-app is at its
      // root (canGoBack=false) should a pop be treated as an exit attempt.
      const isHashRouting = window.location.hash.startsWith("#/");
      if (isHashRouting && navigation.canGoBack()) {
        return;
      }

      const state = window.history.state as HistoryState;

      /**
       * If we're still sitting on the sentinel, this popstate was not
       * the sentinel being popped.
       *
       * Let the browser/Next.js handle it normally.
       */
      if (state?.[BACK_TRAP_KEY]) {
        return;
      }

      handlingBackRef.current = true;

      try {
        /**
         * IMPORTANT:
         *
         * The browser has already moved backwards at this point.
         *
         * Restore the sentinel BEFORE asking the mini app to navigate.
         */
        await restoreTrap().catch(() => {
          // Sentinel could not be restored (e.g. no forward entry); continue
          // best-effort so the press still reaches the mini app instead of
          // hanging forever.
        });

        /**
         * Now the browser is back at:
         *
         *   MiniApp → SENTINEL
         *
         * Ask the mini app to handle the back operation.
         *
         * The mini app's MemoryRouter will do:
         *
         *   /user/profile/12
         *          ↓
         *   /user/profile
         */
        const consumed = await navigation.requestBack();

        if (consumed) {
          /**
           * Nothing else needs to be added to browser history.
           *
           * The sentinel we restored above is already there.
           *
           * Do NOT push another sentinel.
           */
          return;
        }

        /**
         * Mini app has no internal route left.
         *
         * The mini app is now at its entry route, e.g.:
         *
         *   /user
         *
         * Therefore the shell should leave the mini app.
         */
        onExitRef.current();
      } catch (error) {
        console.error("[MiniAppBackButton] Failed to handle browser back:", error);
      } finally {
        handlingBackRef.current = false;
      }
    };

    /**
     * Put one sentinel behind the mini app when it mounts.
     */
    armTrap();

    window.addEventListener("popstate", handlePopState);

    return () => {
      window.removeEventListener("popstate", handlePopState);

      unsubscribeRouteChanged();

      navigation.resetRouter();
    };
  }, [enabled, services, eventBus, armTrap]);
}
